name: surveykit_example
description: Demonstrates how to use the surveykit plugin.

publish_to: 'none'

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  rxdart: ^0.27.5
  audioplayers: ^1.1.1
  bloc: ^8.0.3
  camera: ^0.10.0+1
  cloud_firestore: ^3.1.9
  collection: ^1.15.0
  csv: ^5.0.1
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  firebase_core: ^1.12.0
  flutter_bloc: ^8.0.1
  flutter_platform_widgets: ^1.20.0
  firebase_auth: ^3.3.8
  go_router: ^3.1.1
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  json_annotation: ^4.0.1
  lottie: ^1.0.1
  provider: ^6.0.2
  uuid: ^3.0.4
  video_player: ^2.1.6



dev_dependencies:
  build_runner: ^2.0.4
  json_serializable: ^6.1.3

flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/Q2/
  - assets/Q3/
  - assets/Q4/
  - assets/example_json.json
