// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1nuOc-OMVNHvqNKDbDbJteMDhjiDz0NY',
    appId: '1:482462884629:web:18a6b98576889427997f1c',
    messagingSenderId: '482462884629',
    projectId: 'dissonance-survey-1',
    authDomain: 'dissonance-survey-1.firebaseapp.com',
    storageBucket: 'dissonance-survey-1.appspot.com',
    measurementId: 'G-BT2V9JWXNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2IB4_eMs9f4xalQpqgxcvYuM6da70S-0',
    appId: '1:482462884629:android:675b70533b042cb8997f1c',
    messagingSenderId: '482462884629',
    projectId: 'dissonance-survey-1',
    storageBucket: 'dissonance-survey-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6wIqjpWQRE1k3JEj99sdlHeKhrkjo_1k',
    appId: '1:482462884629:ios:1d6606aa4c2d6511997f1c',
    messagingSenderId: '482462884629',
    projectId: 'dissonance-survey-1',
    storageBucket: 'dissonance-survey-1.appspot.com',
    iosClientId: '482462884629-92ktv75a6sn349gf1i3a4hr0kpf5m5e9.apps.googleusercontent.com',
    iosBundleId: 'com.quickbirdstudios.SurveyKitExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6wIqjpWQRE1k3JEj99sdlHeKhrkjo_1k',
    appId: '1:482462884629:ios:0c690a00dde07dea997f1c',
    messagingSenderId: '482462884629',
    projectId: 'dissonance-survey-1',
    storageBucket: 'dissonance-survey-1.appspot.com',
    iosClientId: '482462884629-6pqkasrhq93f6t519caq9c93gl8fqb6t.apps.googleusercontent.com',
    iosBundleId: 'com.quickbirdstudios.example',
  );
}
